name: Test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read CURRENT_CHANGELOG.md file
        id: getversion
        run: echo "version=\"$(cat ./CURRENT_CHANGELOG.md)\"<<EOF" >> $GITHUB_OUTPUT

      - name: Discord notification
        env:
          DISCORD_EMBEDS: |
            [
              {
                "timestamp": "${{ steps.getversion.outputs.version }}",
              }
            ]
        run: echo $DISCORD_EMBEDS
